# Generated by Django 4.2.3 on 2023-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id_number', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('district', models.CharField(default='', max_length=100)),
                ('school_name', models.CharField(default='', max_length=100)),
                ('profession', models.CharField(choices=[('Service', 'Service'), ('Business', 'Business'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('Housewife', 'House wife'), ('Other', 'Other')], default='আমিরুল ইসলাম মিরন: 01716953986', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=6)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='B+', max_length=3)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_coming', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3)),
                ('participant_image', models.ImageField(blank=True, upload_to='')),
                ('spouse_image', models.ImageField(blank=True, upload_to='')),
                ('paid_at', models.CharField(choices=[('আমিরুল ইসলাম মিরন: 01776411919', 'আমিরুল ইসলাম মিরন: 01776411919'), ('জাকির হোসেন: 01988-691379', 'জাকির হোসেন: 01988-691379'), ('লায়ন মিজানুর রহমান: 01711-530423', 'লায়ন মিজানুর রহমান: 01711-530423'), ('বজলুর রহমান: 01678-054214', 'বজলুর রহমান: 01678-054214'), ('মাহবুবুল হক (মাহবুব): 01762-085059', 'মাহবুবুল হক (মাহবুব): 01762-085059')], default='1000', max_length=35)),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(default=1000)),
                ('transport', models.CharField(choices=[('launch', 'Launch'), ('bus', 'Bus')], default='launch', max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
