# Generated by Django 4.2.3 on 2023-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_picture', models.ImageField(upload_to='participant_pictures')),
                ('spouse_picture', models.ImageField(upload_to='spouse_pictures')),
                ('id_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
