# Generated by Django 4.2.3 on 2023-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='participant',
            name='paid_at',
            field=models.CharField(choices=[('আমিরুল ইসলাম মিরন: 01776411919', 'আমিরুল ইসলাম মিরন: 01776411919'), ('জাকির হোসেন: 01988-691379', 'জাকির হোসেন: 01988-691379'), ('লায়ন মিজানুর রহমান: 01711-530423', 'লায়ন মিজানুর রহমান: 01711-530423'), ('বজলুর রহমান: 01678-054214', 'বজলুর রহমান: 01678-054214'), ('মাহবুবুল হক (মাহবুব): 01762-085059', 'মাহবুবুল হক (মাহবুব): 01762-085059')], default='আমিরুল ইসলাম মিরন: 01716953986', max_length=35),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profession',
            field=models.CharField(choices=[('Service', 'Service'), ('Business', 'Business'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('Housewife', 'House wife'), ('Other', 'Other')], default='Service', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='school_name',
            field=models.CharField(default='', max_length=28),
        ),
        migrations.AlterField(
            model_name='participant',
            name='transaction_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='transport',
            field=models.CharField(choices=[('launch', 'Launch'), ('bus', 'Bus')], default='launch', max_length=10),
        ),
    ]
