# Generated by Django 4.2.3 on 2023-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='district',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_picture',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='spouse_picture',
        ),
        migrations.AddField(
            model_name='participant',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='participant',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='B+', max_length=3),
        ),
        migrations.AddField(
            model_name='participant',
            name='driver_coming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_image',
            field=models.ImageField(blank=True, upload_to='participant_images/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='profession',
            field=models.CharField(choices=[('service', 'Service'), ('business', 'Business'), ('engineer', 'Engineer'), ('doctor', 'Doctor'), ('lawyer', 'Lawyer'), ('housewife', 'House wife'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='school_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='spouse_image',
            field=models.ImageField(blank=True, upload_to='spouse_images/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='spouse_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
