# Generated by Django 4.2.3 on 2023-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_participant_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AddField(
            model_name='participant',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='id_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
