# Generated by Django 4.2.3 on 2023-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_participant_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='spouse_coming',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
    ]
