# Generated by Django 4.2.3 on 2023-07-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_participant_id_participant_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
