# Generated by Django 4.2.3 on 2023-07-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_participant_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='transport',
            field=models.CharField(choices=[('launch', 'Launch'), ('bus', 'Bus')], default='launch', max_length=6),
        ),
        migrations.AlterField(
            model_name='participant',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
