# Generated by Django 4.2.3 on 2023-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_participant_spouse_coming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='paid_at',
            field=models.CharField(choices=[('জাকির হোসেন: 01988-691379', 'জাকির হোসেন: 01988-691379'), ('লায়ন মিজানুর রহমান: 01711-530423', 'লায়ন মিজানুর রহমান: 01711-530423'), ('মাহবুবুল হক (মাহবুব): 01762-085059', 'মাহবুবুল হক (মাহবুব): 01762-085059')], default='আমিরুল ইসলাম মিরন: 01716953986', max_length=35),
        ),
        migrations.AlterField(
            model_name='participant',
            name='school_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='transport',
            field=models.CharField(choices=[('launch', 'Launch'), ('self', 'Self')], default='launch', max_length=10),
        ),
    ]
