# Generated by Django 4.2.3 on 2023-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_participant_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='driver_coming',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='participant',
            name='spouse_coming',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
