# Generated by Django 4.2.3 on 2023-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_participant_transport_alter_participant_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='driver_coming',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='M', max_length=1),
        ),
    ]
