# Generated by Django 4.2.3 on 2023-07-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_participant_driver_coming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
    ]
