# Generated by Django 4.2.3 on 2023-07-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_participant_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='school_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
