# Generated by Django 4.2.3 on 2023-07-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_participant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
