# Generated by Django 4.2.3 on 2023-07-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_participant_spouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
