# Generated by Django 4.2.3 on 2023-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_participant_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='paid_at',
            field=models.CharField(choices=[('আমিরুল ইসলাম মিরন: 01716953986', 'আমিরুল ইসলাম মিরন: 01716953986'), ('জাকির হোসেন: 01988-691379', 'জাকির হোসেন: 01988-691379'), ('লায়ন মিজানুর রহমান: 01711-530423', 'লায়ন মিজানুর রহমান: 01711-530423'), ('বজলুর রহমান: 01678-054214', 'বজলুর রহমান: 01678-054214'), ('মাহবুবুল হক (মাহবুব): 01762-085059', 'মাহবুবুল হক (মাহবুব): 01762-085059')], default='1000', max_length=35),
        ),
    ]
