# Generated by Django 4.2.3 on 2023-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_participant_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profession',
            field=models.CharField(choices=[('service', 'Service'), ('business', 'Business'), ('engineer', 'Engineer'), ('doctor', 'Doctor'), ('lawyer', 'Lawyer'), ('housewife', 'House wife'), ('other', 'Other')], default='আমিরুল ইসলাম মিরন: 01716953986', max_length=100),
        ),
    ]
