# Generated by Django 4.2.3 on 2023-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_participant_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='amount',
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profession',
            field=models.CharField(choices=[('Service', 'Service'), ('Business', 'Business'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('Housewife', 'House wife'), ('Other', 'Other')], default='আমিরুল ইসলাম মিরন: 01716953986', max_length=100),
        ),
    ]
