# Generated by Django 4.2.3 on 2023-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_participant_amount_alter_participant_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
    ]
