# Generated by Django 4.2.3 on 2023-07-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_participant_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='paid_at',
            field=models.CharField(choices=[('আমিরুল ইসলাম মিরন: 01776411919', 'আমিরুল ইসলাম মিরন: 01776411919'), ('জাকির হোসেন: 01988-691379', 'জাকির হোসেন: 01988-691379'), ('লায়ন মিজানুর রহমান: 01711-530423', 'লায়ন মিজানুর রহমান: 01711-530423'), ('বজলুর রহমান: 01678-054214', 'বজলুর রহমান: 01678-054214'), ('মাহবুবুল হক (মাহবুব): 01762-085059', 'মাহবুবুল হক (মাহবুব): 01762-085059')], default='1000', max_length=35),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='spouse_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
